#!/usr/bin/env python3
# openpilot服务定义文件 - 定义系统中所有服务的配置参数
from enum import IntEnum
from typing import Optional


# TODO: 这应该通过capnp schema自动确定
# 队列大小枚举 - 定义不同类型数据的缓冲区大小
class QueueSize(IntEnum):
  BIG = 10 * 1024 * 1024      # 10MB - 视频帧，大型AI输出
  MEDIUM = 2 * 1024 * 1024    # 2MB - 高频数据(CAN)，直播流
  SMALL = 250 * 1024          # 250KB - 大多数服务


# 服务类 - 封装每个服务的配置参数
class Service:
  def __init__(self, should_log: bool, frequency: float, decimation: Optional[int] = None,
               queue_size: QueueSize = QueueSize.SMALL):
    self.should_log = should_log      # 是否记录日志
    self.frequency = frequency        # 服务频率(Hz)
    self.decimation = decimation      # 抽取率(可选)
    self.queue_size = queue_size      # 队列大小


# 服务配置字典 - 定义所有系统服务及其参数
_services: dict[str, tuple] = {
  # 服务名: (是否记录日志, 频率, qlog抽取率(可选), 队列大小(可选))
  # 注意: "EncodeIdx"数据包仍会保留在日志中
  # 传感器数据
  "gyroscope": (True, 104., 104),           # 陀螺仪
  "accelerometer": (True, 104., 104),       # 加速度计
  "magnetometer": (True, 25.),              # 磁力计
  "lightSensor": (True, 100., 100),         # 光线传感器
  "temperatureSensor": (True, 2., 200),     # 温度传感器
  # GPS和设备状态
  "gpsNMEA": (True, 9.),                    # GPS NMEA数据
  "deviceState": (True, 2., 1),             # 设备状态
  "touch": (True, 20., 1),                  # 触摸事件
  # 控制和通信
  "can": (True, 100., 2053, QueueSize.BIG),        # CAN总线数据，抽取后完整段约3条消息
  "controlsState": (True, 100., 10, QueueSize.MEDIUM),  # 控制状态
  "selfdriveState": (True, 100., 10),               # 自动驾驶状态
  "pandaStates": (True, 10., 1),                    # Panda设备状态
  "peripheralState": (True, 2., 1),                 # 外设状态
  # 感知和跟踪
  "radarState": (True, 20., 5),                     # 雷达状态
  "roadEncodeIdx": (False, 20., 1),                 # 道路编码索引
  "liveTracks": (True, 20.),                        # 实时目标跟踪
  "sendcan": (True, 100., 139, QueueSize.MEDIUM),  # 发送CAN数据
  "logMessage": (True, 0.),
  "errorLogMessage": (True, 0., 1),
  "liveCalibration": (True, 4., 4),
  "liveTorqueParameters": (True, 4., 1),
  "liveDelay": (True, 4., 1),
  "androidLog": (True, 0.),
  # 车辆控制
  "carState": (True, 100., 10),                     # 车辆状态
  "carControl": (True, 100., 10),                   # 车辆控制指令
  "carOutput": (True, 100., 10),                    # 车辆输出
  "longitudinalPlan": (True, 20., 10),              # 纵向规划
  "driverAssistance": (True, 20., 20),              # 驾驶辅助
  "procLog": (True, 0.5, 15, QueueSize.BIG),
  "gpsLocationExternal": (True, 10., 10),
  "gpsLocation": (True, 1., 1),
  "ubloxGnss": (True, 10.),
  "qcomGnss": (True, 2.),
  "gnssMeasurements": (True, 10., 10),
  "clocks": (True, 0.1, 1),
  "ubloxRaw": (True, 20.),
  "livePose": (True, 20., 4),
  "liveParameters": (True, 20., 5),
  "cameraOdometry": (True, 20., 10),
  "thumbnail": (True, 1 / 60., 1),
  "onroadEvents": (True, 1., 1),
  "carParams": (True, 0.02, 1),
  "roadCameraState": (True, 20., 20),
  "driverCameraState": (True, 20., 20),
  "driverEncodeIdx": (False, 20., 1),
  "driverStateV2": (True, 20., 10),
  "driverMonitoringState": (True, 20., 10),
  "wideRoadEncodeIdx": (False, 20., 1),
  "wideRoadCameraState": (True, 20., 20),
  # AI模型数据
  "drivingModelData": (True, 20., 10),              # 驾驶模型数据
  "modelV2": (True, 20., None, QueueSize.BIG),      # 模型V2输出
  "managerState": (True, 2., 1),
  "uploaderState": (True, 0., 1),
  "navInstruction": (True, 1., 10),
  "navRoute": (True, 0.),
  "navThumbnail": (True, 0.),
  "qRoadEncodeIdx": (False, 20.),
  "userBookmark": (True, 0., 1),
  "soundPressure": (True, 10., 10),
  "rawAudioData": (False, 20.),
  "bookmarkButton": (True, 0., 1),
  "audioFeedback": (True, 0., 1),
  "roadEncodeData": (False, 20., None, QueueSize.BIG),
  "driverEncodeData": (False, 20., None, QueueSize.BIG),
  "wideRoadEncodeData": (False, 20., None, QueueSize.BIG),
  "qRoadEncodeData": (False, 20., None, QueueSize.BIG),

  # 调试服务
  "uiDebug": (True, 0., 1),                         # UI调试信息
  "testJoystick": (True, 0.),
  "alertDebug": (True, 20., 5),
  "livestreamWideRoadEncodeIdx": (False, 20.),
  "livestreamRoadEncodeIdx": (False, 20.),
  "livestreamDriverEncodeIdx": (False, 20.),
  "livestreamWideRoadEncodeData": (False, 20., None, QueueSize.MEDIUM),
  "livestreamRoadEncodeData": (False, 20., None, QueueSize.MEDIUM),
  "livestreamDriverEncodeData": (False, 20., None, QueueSize.MEDIUM),
  "customReservedRawData0": (True, 0.),
  "customReservedRawData1": (True, 0.),
  "customReservedRawData2": (True, 0.),
}
# 将服务配置转换为Service对象字典
SERVICE_LIST = {name: Service(*vals) for
                idx, (name, vals) in enumerate(_services.items())}


# 生成C++头文件的函数
def build_header():
  h = ""
  h += "/* THIS IS AN AUTOGENERATED FILE, PLEASE EDIT services.py */\n"
  h += "#ifndef __SERVICES_H\n"
  h += "#define __SERVICES_H\n"

  h += "#include <map>\n"
  h += "#include <string>\n"

  # 定义C++服务结构体和映射
  h += "struct service { std::string name; bool should_log; float frequency; int decimation; size_t queue_size; };\n"
  h += "static std::map<std::string, service> services = {\n"
  # 遍历所有服务并生成C++代码
  for k, v in SERVICE_LIST.items():
    should_log = "true" if v.should_log else "false"
    decimation = -1 if v.decimation is None else v.decimation
    h += '  { "%s", {"%s", %s, %f, %d, %d}},\n' % \
         (k, k, should_log, v.frequency, decimation, v.queue_size)
  h += "};\n"

  h += "#endif\n"
  return h


if __name__ == "__main__":
  print(build_header())
